if( TARGET gflags)
    return()
endif()

set(PKG_CONFIG_USE_CMAKE_PREFIX_PATH ON)
find_package(PkgConfig)
pkg_check_modules(GFLAGS QUIET gflags)
function (CompareVersion REQUEST_VERSION LOCAL_VERSION RESULT)
    # set(REQUEST_VERSION ${ARGV0})
    # set(LOCAL_VERSION ${ARGV1})
    string(REPLACE "." ";" REQUEST_VERSION_LIST ${REQUEST_VERSION})
    list(LENGTH REQUEST_VERSION_LIST REQUEST_VERSION_COUNT)
    while(${REQUEST_VERSION_COUNT} LESS 4)
        list(APPEND REQUEST_VERSION_LIST 0)
        list(LENGTH REQUEST_VERSION_LIST REQUEST_VERSION_COUNT)
    endwhile()
    #message(STATUS "REQUEST_VERSION_LIST:${REQUEST_VERSION_LIST}")
    string(REPLACE "." ";" LOCAL_VERSION_LIST ${LOCAL_VERSION})
    list(LENGTH LOCAL_VERSION_LIST LOCAL_VERSION_COUNT)
    while(${LOCAL_VERSION_COUNT} LESS 4)
        list(APPEND LOCAL_VERSION_LIST 0)
        list(LENGTH LOCAL_VERSION_LIST LOCAL_VERSION_COUNT)
    endwhile()
    #message(STATUS "LOCAL_VERSION_LIST:${LOCAL_VERSION_LIST}")
    list(GET REQUEST_VERSION_LIST 0 REQUEST_VERSION_MAJOR)
    list(GET LOCAL_VERSION_LIST 0 LOCAL_VERSION_MAJOR)
    #message(STATUS "MAJOR:${REQUEST_VERSION_MAJOR} ${LOCAL_VERSION_MAJOR}")
    if(REQUEST_VERSION_MAJOR LESS LOCAL_VERSION_MAJOR)
        set(${RESULT} ON PARENT_SCOPE)
        return()
    elseif(GFlags_FIND_VERSION_MAJOR GREATER GFLAGS_VERSION_MAJOR)
        #set(${RESULT} OFF)
        return ()
    else()
    endif()
    #message(STATUS "RESULT:${RESULT}:${${RESULT}}")

    list(GET REQUEST_VERSION_LIST 1 REQUEST_VERSION_MINOR)
    list(GET LOCAL_VERSION_LIST 1 LOCAL_VERSION_MINOR)
    #message(STATUS "MINOR:${REQUEST_VERSION_MINOR} ${LOCAL_VERSION_MINOR}")
    if(REQUEST_VERSION_MINOR LESS LOCAL_VERSION_MINOR)
        set(${RESULT} ON PARENT_SCOPE)
        return()
    elseif(GFlags_FIND_VERSION_MINOR GREATER GFLAGS_VERSION_MINOR)
        #set(${RESULT} OFF)
        return ()
    else()
    endif()

    #message(STATUS "RESULT:${RESULT}")

    list(GET REQUEST_VERSION_LIST 2 REQUEST_VERSION_PATCH)
    list(GET LOCAL_VERSION_LIST 2 LOCAL_VERSION_PATCH)
    #message(STATUS "PATCH:${REQUEST_VERSION_PATCH} ${LOCAL_VERSION_PATCH}")
    if(REQUEST_VERSION_PATCH LESS LOCAL_VERSION_PATCH)
        set(${RESULT} ON PARENT_SCOPE)
        return()
    elseif(GFlags_FIND_VERSION_PATCH GREATER GFLAGS_VERSION_PATCH)
        #set(${RESULT} OFF)
        return ()
    else()
    endif()

    #message(STATUS "RESULT:${RESULT}")

    list(GET REQUEST_VERSION_LIST 3 REQUEST_VERSION_TWEAK)
    list(GET LOCAL_VERSION_LIST 3 LOCAL_VERSION_TWEAK)
    #message(STATUS "TWEAK:${REQUEST_VERSION_TWEAK} ${LOCAL_VERSION_TWEAK}")
    if(REQUEST_VERSION_TWEAK GREATER LOCAL_VERSION_TWEAK)
        #set(${RESULT} OFF)
        return()
    else()
        set(${RESULT} ON PARENT_SCOPE)
        return()
    endif()

endfunction()
# message(STATUS "GFLAGS_FOUND:${GFLAGS_FOUND}")
if(GFLAGS_FOUND)
    # message(STATUS "GFLAGS_LIBRARIES:${GFLAGS_LIBRARIES}")
    # message(STATUS "GFLAGS_LINK_LIBRARIES:${GFLAGS_LINK_LIBRARIES}")
    # message(STATUS "GFLAGS_LIBRARY_DIRS:${GFLAGS_LIBRARY_DIRS}")
    # message(STATUS "GFLAGS_LDFLAGS:${GFLAGS_LDFLAGS}")
    # message(STATUS "GFLAGS_LDFLAGS_OTHER:${GFLAGS_LDFLAGS_OTHER}")
    # message(STATUS "GFLAGS_INCLUDE_DIRS:${GFLAGS_INCLUDE_DIRS}")
    # message(STATUS "GFLAGS_CFLAGS:${GFLAGS_CFLAGS}")
    # message(STATUS "GFLAGS_CFLAGS_OTHER:${GFLAGS_CFLAGS_OTHER}")

    # message(STATUS "GFLAGS_VERSION:${GFLAGS_VERSION}")
    # message(STATUS "GFLAGS_PREFIX:${GFLAGS_PREFIX}")
    # message(STATUS "GFLAGS_INCLUDEDIR:${GFLAGS_INCLUDEDIR}")
    # message(STATUS "GFLAGS_LIBDIR:${GFLAGS_LIBDIR}")
    # message(STATUS "find version:${GFlags_FIND_VERSION}")
    if(GFlags_FIND_VERSION)
        CompareVersion(${GFlags_FIND_VERSION} ${GFLAGS_VERSION} VERSION_OK)
        #message(STATUS "VERSION_OK:${VERSION_OK}")
        if(NOT VERSION_OK)
            if(GFlags_FIND_REQUIRED)
                message(FATAL_ERROR "GFlags not found")
            else()
                message(WARNING "GFlags not found")
            endif()
        endif()
        
    endif()

    # find_library(GFlags_LIBRARY NAMES libgflags.so gflags.dylib gflags.dll
    #     PATHS ${GFLAGS_LIBDIR} ${GFLAGS_LIBRARY_DIRS})
    # find_library(GFlags_STATIC_LIBRARY NAMES libgflags.a gflags_a.a gflags.dll.a
    #     PATHS ${GFLAGS_LIBDIR} ${GFLAGS_LIBRARY_DIRS})
    find_library(GFlags_LIBRARY NAMES libgflags.a gflags_a.a gflags.dll.a
        PATHS ${GFLAGS_LIBDIR} ${GFLAGS_LIBRARY_DIRS})
    # message(STATUS "GFlags_LIBRARY:${GFlags_LIBRARY}")
    # message(STATUS "FOUND:${GFlags_LIBRARY}")
    if(GFlags_LIBRARY  )
        set(GFlags_FOUND ON)
        set(GFlags_VERSION ${GFLAGS_VERSION})
        set(GFlags_INCLUDE_DIR ${GFLAGS_INCLUDE_DIRS})
        set(GFlags_LIBRARY_DIR ${GFLAGS_INCLUDE_DIRS})
        message(STATUS "Found GFlags ${GFlags_LIBRARY} version:${GFlags_VERSION}")

        # add_library(gflags SHARED IMPORTED )
        # set_property(TARGET gflags PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${GFLAGS_INCLUDEDIR})
        # set_property(TARGET gflags PROPERTY IMPORTED_LOCATION ${GFlags_LIBRARY})
        
        # add_library(gflags-static STATIC IMPORTED )
        # set_property(TARGET gflags-static PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${GFLAGS_INCLUDEDIR})
        # set_property(TARGET gflags-static PROPERTY IMPORTED_LOCATION ${GFlags_STATIC_LIBRARY})
        add_library(gflags STATIC IMPORTED )
        set_property(TARGET gflags PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${GFLAGS_INCLUDEDIR})
        set_property(TARGET gflags PROPERTY IMPORTED_LOCATION ${GFlags_LIBRARY})
    endif()
else()
    if(GFlags_FIND_REQUIRED)
        message(FATAL_ERROR "GFlags not found")
    else()
        message(WARNING "GFlags not found")
    endif()
endif()



